# 1. Creating Tensors in PyTorch

Tensors are like arrays in NumPy, but designed for deep learning!
They can store numbers and perform operations efficiently on GPUs.


In [1]:
import torch
import numpy as np


## 1. Creating Tensors from Lists

The simplest way: create a tensor from a Python list!


In [2]:
# Create a tensor from a list
t1 = torch.tensor([1, 2, 3, 4, 5])
print("1D tensor:")
print(t1)
print(f"Shape: {t1.shape}")
print(f"Size: {t1.size()}")
print()

# Create a 2D tensor (matrix)
t2 = torch.tensor([[1, 2, 3], 
                   [4, 5, 6]])
print("2D tensor (matrix):")
print(t2)
print(f"Shape: {t2.shape}")
print()

# Create a 3D tensor
t3 = torch.tensor([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("3D tensor:")
print(t3)
print(f"Shape: {t3.shape}")
print(f"Number of dimensions: {t3.dim()}")


1D tensor:
tensor([1, 2, 3, 4, 5])
Shape: torch.Size([5])
Size: torch.Size([5])

2D tensor (matrix):
tensor([[1, 2, 3],
        [4, 5, 6]])
Shape: torch.Size([2, 3])

3D tensor:
tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])
Shape: torch.Size([2, 2, 2])
Number of dimensions: 3


## 2. Creating Tensors with Zeros and Ones

Create tensors filled with zeros or ones of a specific shape!


In [3]:
# Create tensor filled with zeros
zeros_1d = torch.zeros(5)
print("1D tensor of zeros:")
print(zeros_1d)
print()

zeros_2d = torch.zeros(3, 4)
print("2D tensor of zeros (3 rows, 4 columns):")
print(zeros_2d)
print()

# Create tensor filled with ones
ones_1d = torch.ones(5)
print("1D tensor of ones:")
print(ones_1d)
print()

ones_2d = torch.ones(2, 3)
print("2D tensor of ones (2 rows, 3 columns):")
print(ones_2d)
print()

# Create tensor with specific value
full_tensor = torch.full((2, 3), 5.0)
print("2D tensor filled with 5.0:")
print(full_tensor)


1D tensor of zeros:
tensor([0., 0., 0., 0., 0.])

2D tensor of zeros (3 rows, 4 columns):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

1D tensor of ones:
tensor([1., 1., 1., 1., 1.])

2D tensor of ones (2 rows, 3 columns):
tensor([[1., 1., 1.],
        [1., 1., 1.]])

2D tensor filled with 5.0:
tensor([[5., 5., 5.],
        [5., 5., 5.]])


## 3. Creating Tensors from NumPy Arrays

Convert NumPy arrays to PyTorch tensors easily!


In [4]:
# Create NumPy array
np_array = np.array([1, 2, 3, 4, 5])
print("NumPy array:")
print(np_array)
print(type(np_array))
print()

# Convert to PyTorch tensor
torch_tensor = torch.from_numpy(np_array)
print("PyTorch tensor (from NumPy):")
print(torch_tensor)
print(type(torch_tensor))
print()

# Convert PyTorch tensor to NumPy
tensor_back = torch.tensor([1, 2, 3, 4, 5])
np_array_back = tensor_back.numpy()
print("Converted back to NumPy:")
print(np_array_back)
print(type(np_array_back))
print()

# Note: They share memory if using from_numpy()!
print("Note: torch.from_numpy() shares memory with NumPy array!")
print("Changes to one affect the other (unless you use .clone())")


NumPy array:
[1 2 3 4 5]
<class 'numpy.ndarray'>

PyTorch tensor (from NumPy):
tensor([1, 2, 3, 4, 5])
<class 'torch.Tensor'>

Converted back to NumPy:
[1 2 3 4 5]
<class 'numpy.ndarray'>

Note: torch.from_numpy() shares memory with NumPy array!
Changes to one affect the other (unless you use .clone())


## 4. Creating Tensors with Random Values

Generate random tensors for initializing neural networks!


In [5]:
# Random values between 0 and 1
random_tensor = torch.rand(3, 4)
print("Random tensor (values between 0 and 1):")
print(random_tensor)
print()

# Random integers
random_int = torch.randint(0, 10, (3, 4))
print("Random integers (0 to 9):")
print(random_int)
print()

# Random values from normal distribution (mean=0, std=1)
normal_tensor = torch.randn(3, 4)
print("Random values from normal distribution:")
print(normal_tensor)
print()

# Random values with specific range
random_range = torch.rand(3, 4) * 10  # Scale to 0-10
print("Random values scaled to 0-10:")
print(random_range)


Random tensor (values between 0 and 1):
tensor([[0.3797, 0.7568, 0.4673, 0.2231],
        [0.0692, 0.7387, 0.3445, 0.9549],
        [0.5787, 0.3985, 0.4419, 0.7837]])

Random integers (0 to 9):
tensor([[6, 0, 7, 2],
        [4, 9, 7, 0],
        [7, 8, 5, 1]])

Random values from normal distribution:
tensor([[-0.3674, -1.4438, -0.4425, -0.2274],
        [-1.7687,  0.2896,  0.4027,  0.8825],
        [-0.5602,  1.3057, -1.4657, -0.8988]])

Random values scaled to 0-10:
tensor([[8.2510, 4.5628, 9.4352, 7.8575],
        [2.2711, 2.4427, 6.5990, 9.2377],
        [0.3826, 7.5882, 6.6383, 3.3190]])


## 5. Data Types (dtype)

Tensors can have different data types: float32, int64, etc.
Specify the type when creating tensors!


In [6]:
# Default float tensor
t_float = torch.tensor([1.0, 2.0, 3.0])
print("Float tensor (default):")
print(t_float)
print(f"dtype: {t_float.dtype}")
print()

# Integer tensor
t_int = torch.tensor([1, 2, 3], dtype=torch.int64)
print("Integer tensor:")
print(t_int)
print(f"dtype: {t_int.dtype}")
print()

# Float32 tensor (most common for neural networks)
t_float32 = torch.tensor([1.0, 2.0, 3.0], dtype=torch.float32)
print("Float32 tensor:")
print(t_float32)
print(f"dtype: {t_float32.dtype}")
print()

# Convert between types
t_convert = torch.tensor([1, 2, 3], dtype=torch.int64)
t_float_converted = t_convert.float()
print("Converted to float:")
print(t_float_converted)
print(f"dtype: {t_float_converted.dtype}")
print()

# Common dtypes
print("Common dtypes:")
print(f"torch.float32 (or torch.float): 32-bit float")
print(f"torch.float64 (or torch.double): 64-bit float")
print(f"torch.int32 (or torch.int): 32-bit integer")
print(f"torch.int64 (or torch.long): 64-bit integer")


Float tensor (default):
tensor([1., 2., 3.])
dtype: torch.float32

Integer tensor:
tensor([1, 2, 3])
dtype: torch.int64

Float32 tensor:
tensor([1., 2., 3.])
dtype: torch.float32

Converted to float:
tensor([1., 2., 3.])
dtype: torch.float32

Common dtypes:
torch.float32 (or torch.float): 32-bit float
torch.float64 (or torch.double): 64-bit float
torch.int32 (or torch.int): 32-bit integer
torch.int64 (or torch.long): 64-bit integer


## 6. Key Takeaways

**Creating tensors:**
- `torch.tensor([...])` - from list
- `torch.zeros(shape)` - filled with zeros
- `torch.ones(shape)` - filled with ones
- `torch.rand(shape)` - random values (0-1)
- `torch.randn(shape)` - random from normal distribution
- `torch.from_numpy(array)` - from NumPy array

**Important properties:**
- `tensor.shape` - dimensions of tensor
- `tensor.dtype` - data type (float32, int64, etc.)
- `tensor.dim()` - number of dimensions

**Remember:** Tensors are the building blocks of PyTorch!
