# 7. Special Tensors: eye, rand, arange, linspace

Create special tensors for common use cases!
Identity matrices, random values, sequences, and more.


In [1]:
import torch


## 1. eye: Identity Matrix

torch.eye() creates an identity matrix (1s on diagonal, 0s elsewhere)!
Useful for linear algebra operations.


In [2]:
# Create identity matrix
I = torch.eye(3)
print("Identity matrix (3×3):")
print(I)
print(f"Shape: {I.shape}")
print()

# Identity matrix with different dtype
I_float = torch.eye(3, dtype=torch.float32)
print("Identity matrix (float32):")
print(I_float)
print(f"dtype: {I_float.dtype}")
print()

# Non-square identity (rectangular)
I_rect = torch.eye(2, 3)
print("Rectangular identity (2×3):")
print(I_rect)
print(f"Shape: {I_rect.shape}")
print()

# Use case: A @ I = A
A = torch.tensor([[1, 2, 3], 
                  [4, 5, 6]], dtype=torch.float32)
I_3x3 = torch.eye(3, dtype=torch.float32)

result = A @ I_3x3
print("Matrix multiplication with identity:")
print(f"A:")
print(A)
print(f"I:")
print(I_3x3)
print(f"A @ I:")
print(result)
print(f"(Should equal A: {torch.equal(A, result)})")


Identity matrix (3×3):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Shape: torch.Size([3, 3])

Identity matrix (float32):
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
dtype: torch.float32

Rectangular identity (2×3):
tensor([[1., 0., 0.],
        [0., 1., 0.]])
Shape: torch.Size([2, 3])

Matrix multiplication with identity:
A:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
I:
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
A @ I:
tensor([[1., 2., 3.],
        [4., 5., 6.]])
(Should equal A: True)


## 2. rand: Random Values

torch.rand() creates tensors with random values between 0 and 1!
Useful for initializing neural networks.


In [3]:
# Random values between 0 and 1
random_tensor = torch.rand(3, 4)
print("Random tensor (values between 0 and 1):")
print(random_tensor)
print(f"Shape: {random_tensor.shape}")
print()

# Random values with specific range
random_range = torch.rand(2, 3) * 10  # Scale to 0-10
print("Random values scaled to 0-10:")
print(random_range)
print()

# Random integers
random_int = torch.randint(0, 10, (3, 4))
print("Random integers (0 to 9):")
print(random_int)
print(f"Shape: {random_int.shape}")
print()

# Random from normal distribution (mean=0, std=1)
normal_tensor = torch.randn(3, 4)
print("Random from normal distribution:")
print(normal_tensor)
print(f"Mean: {normal_tensor.mean():.3f}")
print(f"Std: {normal_tensor.std():.3f}")
print()

# Random with specific seed (for reproducibility)
torch.manual_seed(42)
random_seed = torch.rand(2, 3)
print("Random with seed=42:")
print(random_seed)
print("(Same seed = same random values!)")


Random tensor (values between 0 and 1):
tensor([[0.1926, 0.8026, 0.2755, 0.1811],
        [0.2480, 0.8767, 0.4530, 0.6584],
        [0.5261, 0.1073, 0.0370, 0.0824]])
Shape: torch.Size([3, 4])

Random values scaled to 0-10:
tensor([[5.8131, 9.5665, 1.7315],
        [1.7535, 8.7158, 5.3893]])

Random integers (0 to 9):
tensor([[8, 3, 4, 5],
        [5, 9, 2, 5],
        [9, 7, 7, 0]])
Shape: torch.Size([3, 4])

Random from normal distribution:
tensor([[ 1.4071,  0.2874, -0.5587, -1.6236],
        [ 0.1103, -0.1113,  0.2255, -1.8327],
        [-0.2289,  2.2509, -0.1232, -1.0589]])
Mean: -0.105
Std: 1.151

Random with seed=42:
tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])
(Same seed = same random values!)


In [4]:
# Create sequence from 0 to 9
seq1 = torch.arange(10)
print("torch.arange(10):")
print(seq1)
print()

# Create sequence with start and end
seq2 = torch.arange(2, 8)
print("torch.arange(2, 8):")
print(seq2)
print()

# Create sequence with step
seq3 = torch.arange(0, 10, 2)
print("torch.arange(0, 10, 2) - step=2:")
print(seq3)
print()

# Create sequence with float values
seq4 = torch.arange(0.0, 5.0, 0.5)
print("torch.arange(0.0, 5.0, 0.5) - float step:")
print(seq4)
print()

# Create sequence with specific dtype
seq5 = torch.arange(10, dtype=torch.float32)
print("torch.arange(10, dtype=torch.float32):")
print(seq5)
print(f"dtype: {seq5.dtype}")
print()

# Reshape arange to 2D
seq_2d = torch.arange(12).reshape(3, 4)
print("arange(12) reshaped to (3, 4):")
print(seq_2d)


torch.arange(10):
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

torch.arange(2, 8):
tensor([2, 3, 4, 5, 6, 7])

torch.arange(0, 10, 2) - step=2:
tensor([0, 2, 4, 6, 8])

torch.arange(0.0, 5.0, 0.5) - float step:
tensor([0.0000, 0.5000, 1.0000, 1.5000, 2.0000, 2.5000, 3.0000, 3.5000, 4.0000,
        4.5000])

torch.arange(10, dtype=torch.float32):
tensor([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])
dtype: torch.float32

arange(12) reshaped to (3, 4):
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


## 4. linspace: Linear Spacing

torch.linspace() creates evenly spaced values in a range!
Specify start, end, and number of points.


In [5]:
# Create 5 evenly spaced values from 0 to 1
lin1 = torch.linspace(0, 1, 5)
print("torch.linspace(0, 1, 5):")
print(lin1)
print()

# Create 10 evenly spaced values from 0 to 10
lin2 = torch.linspace(0, 10, 10)
print("torch.linspace(0, 10, 10):")
print(lin2)
print()

# Create negative to positive range
lin3 = torch.linspace(-5, 5, 11)
print("torch.linspace(-5, 5, 11):")
print(lin3)
print()

# Compare: arange vs linspace
print("=" * 60)
print("COMPARISON: arange vs linspace")
print("=" * 60)
print("arange: Specify step size")
arange_ex = torch.arange(0, 10, 2)
print(f"  torch.arange(0, 10, 2): {arange_ex}")
print()

print("linspace: Specify number of points")
linspace_ex = torch.linspace(0, 8, 5)
print(f"  torch.linspace(0, 8, 5): {linspace_ex}")
print()

print("Difference:")
print("  - arange: You control the step")
print("  - linspace: You control the number of points")


torch.linspace(0, 1, 5):
tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])

torch.linspace(0, 10, 10):
tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

torch.linspace(-5, 5, 11):
tensor([-5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.,  5.])

COMPARISON: arange vs linspace
arange: Specify step size
  torch.arange(0, 10, 2): tensor([0, 2, 4, 6, 8])

linspace: Specify number of points
  torch.linspace(0, 8, 5): tensor([0., 2., 4., 6., 8.])

Difference:
  - arange: You control the step
  - linspace: You control the number of points


## 5. Other Special Tensor Functions

Let's see more useful tensor creation functions!


In [6]:
# ones: Tensor filled with ones
ones = torch.ones(3, 4)
print("torch.ones(3, 4):")
print(ones)
print()

# zeros: Tensor filled with zeros
zeros = torch.zeros(3, 4)
print("torch.zeros(3, 4):")
print(zeros)
print()

# full: Tensor filled with specific value
full = torch.full((3, 4), 5.0)
print("torch.full((3, 4), 5.0):")
print(full)
print()

# empty: Uninitialized tensor (contains garbage values)
empty = torch.empty(3, 4)
print("torch.empty(3, 4) - uninitialized:")
print(empty)
print("(Values are random/garbage - be careful!)")
print()

# Summary
print("=" * 60)
print("SUMMARY OF SPECIAL TENSORS")
print("=" * 60)
print("torch.eye(n) - identity matrix")
print("torch.rand(shape) - random values (0-1)")
print("torch.randn(shape) - random from normal distribution")
print("torch.randint(low, high, shape) - random integers")
print("torch.arange(start, end, step) - sequence with step")
print("torch.linspace(start, end, steps) - evenly spaced values")
print("torch.ones(shape) - filled with ones")
print("torch.zeros(shape) - filled with zeros")
print("torch.full(shape, value) - filled with specific value")
print("torch.empty(shape) - uninitialized (garbage values)")


torch.ones(3, 4):
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

torch.zeros(3, 4):
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

torch.full((3, 4), 5.0):
tensor([[5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.]])

torch.empty(3, 4) - uninitialized:
tensor([[1.0756e-30, 0.0000e+00, 9.1035e-31, 0.0000e+00],
        [2.2421e-44, 7.0065e-45, 1.4013e-45, 0.0000e+00],
        [1.0659e-30, 0.0000e+00, 1.0659e-30, 0.0000e+00]])
(Values are random/garbage - be careful!)

SUMMARY OF SPECIAL TENSORS
torch.eye(n) - identity matrix
torch.rand(shape) - random values (0-1)
torch.randn(shape) - random from normal distribution
torch.randint(low, high, shape) - random integers
torch.arange(start, end, step) - sequence with step
torch.linspace(start, end, steps) - evenly spaced values
torch.ones(shape) - filled with ones
torch.zeros(shape) - filled with zeros
torch.full(shape, value) - filled with specific value
torch

## 6. Key Takeaways

**Special tensor creation:**
- `torch.eye(n)` - identity matrix (n×n)
- `torch.rand(shape)` - random values (0-1)
- `torch.randn(shape)` - random from normal distribution
- `torch.randint(low, high, shape)` - random integers
- `torch.arange(start, end, step)` - sequence with step
- `torch.linspace(start, end, steps)` - evenly spaced values
- `torch.ones(shape)` - filled with ones
- `torch.zeros(shape)` - filled with zeros
- `torch.full(shape, value)` - filled with specific value

**Key differences:**
- **arange**: You specify step size
- **linspace**: You specify number of points
- **rand**: Uniform distribution (0-1)
- **randn**: Normal distribution (mean=0, std=1)

**Remember:** These functions help you create tensors quickly for common use cases!
